-- Atualiza o status operacional da cotacao de frete diretamente no banco.
-- Mantem compatibilidade com insercoes via ERP/N8N e nao remove dados.

CREATE OR REPLACE FUNCTION CONTROLSHUB_CALCULAR_STATUS_COTACAO(
  P_EMPRESA_ID BIGINT,
  P_TIPO_DOCUMENTO VARCHAR,
  P_NUMERO_DOCUMENTO VARCHAR,
  P_CODIGO_CHAVE VARCHAR,
  P_FORCAR_RECALCULO BOOLEAN DEFAULT FALSE
)
RETURNS VOID
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_STATUS_ATUAL VARCHAR(80);
  V_STATUS_NOVO VARCHAR(80);
  V_ORDEM_ATUAL INTEGER;
  V_ORDEM_NOVA INTEGER;
  V_ETAPA_ID BIGINT;
  V_SITUACAO_PEDIDO VARCHAR(80);
  V_TRANSPORTADORA_ESCOLHIDA_ID BIGINT;
  V_NUMERO_CTE VARCHAR(80);
  V_CTE_RECEBIDO_EM TIMESTAMPTZ;
  V_TOTAL_CTES INTEGER;
  V_TOTAL_AUTOMATICAS INTEGER;
  V_TOTAL_TRANSPORTADORAS_FLUXO INTEGER;
  V_TOTAL_TRANSPORTADORAS_RESPONDIDAS INTEGER;
BEGIN
  SELECT
    COALESCE(C.STATUS, '0'),
    COALESCE(C.SITUACAO_PEDIDO, 'ATIVO'),
    C.TRANSPORTADORA_ESCOLHIDA_ID,
    C.NUMERO_CTE,
    C.CTE_RECEBIDO_EM
  INTO
    V_STATUS_ATUAL,
    V_SITUACAO_PEDIDO,
    V_TRANSPORTADORA_ESCOLHIDA_ID,
    V_NUMERO_CTE,
    V_CTE_RECEBIDO_EM
  FROM COTACOES_FRETE C
  WHERE C.EMPRESA_ID = P_EMPRESA_ID
    AND C.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND C.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND C.CODIGO_CHAVE = P_CODIGO_CHAVE
    AND COALESCE(C.EXCLUIDO, FALSE) = FALSE
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT COUNT(*)
  INTO V_TOTAL_CTES
  FROM COTACOES_FRETE_CTES CTE
  WHERE CTE.EMPRESA_ID = P_EMPRESA_ID
    AND CTE.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CTE.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CTE.CODIGO_CHAVE = P_CODIGO_CHAVE;

  SELECT
    COUNT(*) FILTER (
      WHERE (
        CFT.ORIGEM_COTACAO IN ('ERP', 'AUTOMATICA')
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%AUTOMATICA%'
      )
      AND COALESCE(CFT.VALOR_FRETE, 0) > 0
    ),
    COUNT(*) FILTER (
      WHERE COALESCE(CFT.SOLICITADA_POR_LINK, FALSE) = TRUE
         OR CFT.ORIGEM_COTACAO IN ('MANUAL', 'EXTERNA', 'LINK')
         OR UPPER(COALESCE(CFT.STATUS, '')) LIKE '%TRANSPORTADORA%'
         OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%TRANSPORTADORA%'
         OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%DIGITACAO_ERP%'
    ),
    COUNT(*) FILTER (
      WHERE (
        COALESCE(CFT.SOLICITADA_POR_LINK, FALSE) = TRUE
        OR CFT.ORIGEM_COTACAO IN ('MANUAL', 'EXTERNA', 'LINK')
        OR UPPER(COALESCE(CFT.STATUS, '')) LIKE '%TRANSPORTADORA%'
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%TRANSPORTADORA%'
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%DIGITACAO_ERP%'
      )
      AND (
        CFT.STATUS IN ('RESPONDIDA', 'SELECIONADA', 'ALTERADA_MANUALMENTE', 'COTACAO_TRANSPORTADORA_RECEBIDA')
        OR CFT.RESPONDIDA_EM IS NOT NULL
        OR CFT.ORIGEM_COTACAO = 'EXTERNA'
        OR COALESCE(CFT.SELECIONADA, FALSE) = TRUE
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%DIGITACAO_ERP%'
      )
    )
  INTO
    V_TOTAL_AUTOMATICAS,
    V_TOTAL_TRANSPORTADORAS_FLUXO,
    V_TOTAL_TRANSPORTADORAS_RESPONDIDAS
  FROM COTACOES_FRETE_TRANSPORTADORAS CFT
  WHERE CFT.EMPRESA_ID = P_EMPRESA_ID
    AND CFT.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CFT.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CFT.CODIGO_CHAVE = P_CODIGO_CHAVE;

  IF UPPER(COALESCE(V_SITUACAO_PEDIDO, 'ATIVO')) <> 'ATIVO' THEN
    V_STATUS_NOVO := 'COTACAO_CANCELADA';
  ELSIF COALESCE(V_TOTAL_CTES, 0) > 0 OR COALESCE(V_NUMERO_CTE, '') <> '' OR V_CTE_RECEBIDO_EM IS NOT NULL THEN
    V_STATUS_NOVO := 'CTE_EMITIDO';
  ELSIF V_TRANSPORTADORA_ESCOLHIDA_ID IS NOT NULL THEN
    V_STATUS_NOVO := 'TRANSPORTADORA_ESCOLHIDA';
  ELSIF COALESCE(V_TOTAL_TRANSPORTADORAS_FLUXO, 0) > 0 THEN
    IF COALESCE(V_TOTAL_TRANSPORTADORAS_RESPONDIDAS, 0) >= COALESCE(V_TOTAL_TRANSPORTADORAS_FLUXO, 0) THEN
      V_STATUS_NOVO := 'EM_ANALISE';
    ELSE
      V_STATUS_NOVO := 'COTACAO_TRANSPORTADORA';
    END IF;
  ELSIF COALESCE(V_TOTAL_AUTOMATICAS, 0) > 0 THEN
    V_STATUS_NOVO := 'COTACAO_AUTOMATICA';
  ELSE
    V_STATUS_NOVO := 'COTACAO_PENDENTE';
  END IF;

  V_ORDEM_ATUAL := CASE UPPER(COALESCE(V_STATUS_ATUAL, ''))
    WHEN 'COTACAO_PENDENTE' THEN 1
    WHEN 'COTACAO_AUTOMATICA' THEN 2
    WHEN 'COTACAO_TRANSPORTADORA' THEN 3
    WHEN 'EM_ANALISE' THEN 4
    WHEN 'TRANSPORTADORA_ESCOLHIDA' THEN 5
    WHEN 'CTE_EMITIDO' THEN 6
    WHEN 'COTACAO_CANCELADA' THEN 7
    ELSE 0
  END;

  V_ORDEM_NOVA := CASE UPPER(COALESCE(V_STATUS_NOVO, ''))
    WHEN 'COTACAO_PENDENTE' THEN 1
    WHEN 'COTACAO_AUTOMATICA' THEN 2
    WHEN 'COTACAO_TRANSPORTADORA' THEN 3
    WHEN 'EM_ANALISE' THEN 4
    WHEN 'TRANSPORTADORA_ESCOLHIDA' THEN 5
    WHEN 'CTE_EMITIDO' THEN 6
    WHEN 'COTACAO_CANCELADA' THEN 7
    ELSE 0
  END;

  IF NOT P_FORCAR_RECALCULO AND V_ORDEM_NOVA < V_ORDEM_ATUAL THEN
    V_STATUS_NOVO := V_STATUS_ATUAL;
  END IF;

  SELECT EK.ID
  INTO V_ETAPA_ID
  FROM ETAPAS_KANBAN EK
  INNER JOIN MODULOS M
    ON M.ID = EK.MODULO_ID
  WHERE EK.EMPRESA_ID = P_EMPRESA_ID
    AND M.CODIGO = 'COTACAO_FRETE'
    AND EK.CODIGO = V_STATUS_NOVO
    AND EK.ATIVA = TRUE
  ORDER BY EK.ORDEM ASC, EK.ID ASC
  LIMIT 1;

  UPDATE COTACOES_FRETE
  SET STATUS = V_STATUS_NOVO,
    ETAPA_KANBAN_ID = COALESCE(V_ETAPA_ID, ETAPA_KANBAN_ID),
    ALTERADO_EM = NOW()
  WHERE EMPRESA_ID = P_EMPRESA_ID
    AND TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CODIGO_CHAVE = P_CODIGO_CHAVE
    AND COALESCE(EXCLUIDO, FALSE) = FALSE;
END;
$$;

CREATE OR REPLACE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_EMPRESA_ID BIGINT;
  V_TIPO_DOCUMENTO VARCHAR;
  V_NUMERO_DOCUMENTO VARCHAR;
  V_CODIGO_CHAVE VARCHAR;
BEGIN
  IF PG_TRIGGER_DEPTH() > 1 THEN
    RETURN NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    V_EMPRESA_ID := OLD.EMPRESA_ID;
    V_TIPO_DOCUMENTO := OLD.TIPO_DOCUMENTO;
    V_NUMERO_DOCUMENTO := OLD.NUMERO_DOCUMENTO;
    V_CODIGO_CHAVE := OLD.CODIGO_CHAVE;
  ELSE
    V_EMPRESA_ID := NEW.EMPRESA_ID;
    V_TIPO_DOCUMENTO := NEW.TIPO_DOCUMENTO;
    V_NUMERO_DOCUMENTO := NEW.NUMERO_DOCUMENTO;
    V_CODIGO_CHAVE := NEW.CODIGO_CHAVE;
  END IF;

  PERFORM CONTROLSHUB_CALCULAR_STATUS_COTACAO(
    V_EMPRESA_ID,
    V_TIPO_DOCUMENTO,
    V_NUMERO_DOCUMENTO,
    V_CODIGO_CHAVE,
    FALSE
  );

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS TG_CONTROLSHUB_STATUS_COTACAO_CABECALHO ON COTACOES_FRETE;
CREATE TRIGGER TG_CONTROLSHUB_STATUS_COTACAO_CABECALHO
AFTER INSERT OR UPDATE OF STATUS, SITUACAO_PEDIDO, TRANSPORTADORA_ESCOLHIDA_ID, NUMERO_CTE, CTE_RECEBIDO_EM, BLOQUEADO_PARA_ALTERACAO
ON COTACOES_FRETE
FOR EACH ROW
EXECUTE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO();

DROP TRIGGER IF EXISTS TG_CONTROLSHUB_STATUS_COTACAO_TRANSPORTADORA ON COTACOES_FRETE_TRANSPORTADORAS;
CREATE TRIGGER TG_CONTROLSHUB_STATUS_COTACAO_TRANSPORTADORA
AFTER INSERT OR UPDATE OR DELETE
ON COTACOES_FRETE_TRANSPORTADORAS
FOR EACH ROW
EXECUTE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO();

DROP TRIGGER IF EXISTS TG_CONTROLSHUB_STATUS_COTACAO_CTE ON COTACOES_FRETE_CTES;
CREATE TRIGGER TG_CONTROLSHUB_STATUS_COTACAO_CTE
AFTER INSERT OR UPDATE OR DELETE
ON COTACOES_FRETE_CTES
FOR EACH ROW
EXECUTE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO();

DO $$
DECLARE
  REGISTRO RECORD;
BEGIN
  FOR REGISTRO IN
    SELECT EMPRESA_ID, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, CODIGO_CHAVE
    FROM COTACOES_FRETE
    WHERE COALESCE(EXCLUIDO, FALSE) = FALSE
  LOOP
    PERFORM CONTROLSHUB_CALCULAR_STATUS_COTACAO(
      REGISTRO.EMPRESA_ID,
      REGISTRO.TIPO_DOCUMENTO,
      REGISTRO.NUMERO_DOCUMENTO,
      REGISTRO.CODIGO_CHAVE,
      TRUE
    );
  END LOOP;
END;
$$;
