-- Ajusta a regra oficial de status operacional da cotação.
-- Remove a trava que impedia retorno para uma etapa menor quando o dado real não sustentava o status.
-- Considera transportadora escolhida apenas quando houver escolha real auditável.

CREATE OR REPLACE FUNCTION CONTROLSHUB_CALCULAR_STATUS_COTACAO(
  P_EMPRESA_ID BIGINT,
  P_TIPO_DOCUMENTO VARCHAR,
  P_NUMERO_DOCUMENTO VARCHAR,
  P_CODIGO_CHAVE VARCHAR,
  P_FORCAR_RECALCULO BOOLEAN DEFAULT FALSE
)
RETURNS VOID
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_STATUS_NOVO VARCHAR(80);
  V_ETAPA_ID BIGINT;
  V_SITUACAO_PEDIDO VARCHAR(80);
  V_NUMERO_CTE VARCHAR(80);
  V_CTE_RECEBIDO_EM TIMESTAMPTZ;
  V_ESCOLHIDO_EM TIMESTAMPTZ;
  V_ESCOLHIDO_POR_USUARIO_ID BIGINT;
  V_TOTAL_CTES INTEGER;
  V_TOTAL_AUTOMATICAS INTEGER;
  V_TOTAL_TRANSPORTADORAS_FLUXO INTEGER;
  V_TOTAL_TRANSPORTADORAS_RESPONDIDAS INTEGER;
  V_TEM_TRANSPORTADORA_ESCOLHIDA BOOLEAN;
  V_POSSUI_ESCOLHA_REAL BOOLEAN;
BEGIN
  SELECT
    COALESCE(C.SITUACAO_PEDIDO, 'ATIVO'),
    C.NUMERO_CTE,
    C.CTE_RECEBIDO_EM,
    C.ESCOLHIDO_EM,
    C.ESCOLHIDO_POR_USUARIO_ID
  INTO
    V_SITUACAO_PEDIDO,
    V_NUMERO_CTE,
    V_CTE_RECEBIDO_EM,
    V_ESCOLHIDO_EM,
    V_ESCOLHIDO_POR_USUARIO_ID
  FROM COTACOES_FRETE C
  WHERE C.EMPRESA_ID = P_EMPRESA_ID
    AND C.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND C.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND C.CODIGO_CHAVE = P_CODIGO_CHAVE
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT COUNT(*)
  INTO V_TOTAL_CTES
  FROM COTACOES_FRETE_CTES CTE
  WHERE CTE.EMPRESA_ID = P_EMPRESA_ID
    AND CTE.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CTE.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CTE.CODIGO_CHAVE = P_CODIGO_CHAVE;

  SELECT
    COUNT(*) FILTER (
      WHERE UPPER(COALESCE(CFT.ORIGEM_COTACAO, '')) IN ('ERP', 'AUTOMATICA', 'BANCO')
        AND COALESCE(CFT.VALOR_FRETE, 0) > 0
    ),
    COUNT(*) FILTER (
      WHERE COALESCE(CFT.SOLICITADA_POR_LINK, FALSE) = TRUE
        OR UPPER(COALESCE(CFT.ORIGEM_COTACAO, '')) IN ('MANUAL', 'EXTERNA', 'LINK')
        OR UPPER(COALESCE(CFT.STATUS, '')) LIKE '%TRANSPORTADORA%'
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%TRANSPORTADORA%'
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%DIGITACAO_ERP%'
    ),
    COUNT(*) FILTER (
      WHERE (
        COALESCE(CFT.SOLICITADA_POR_LINK, FALSE) = TRUE
        OR UPPER(COALESCE(CFT.ORIGEM_COTACAO, '')) IN ('MANUAL', 'EXTERNA', 'LINK')
        OR UPPER(COALESCE(CFT.STATUS, '')) LIKE '%TRANSPORTADORA%'
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%TRANSPORTADORA%'
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%DIGITACAO_ERP%'
      )
      AND (
        UPPER(COALESCE(CFT.STATUS, '')) IN ('RESPONDIDA', 'SELECIONADA', 'ALTERADA_MANUALMENTE', 'COTACAO_TRANSPORTADORA_RECEBIDA', 'COTADA')
        OR CFT.RESPONDIDA_EM IS NOT NULL
        OR COALESCE(CFT.SELECIONADA, FALSE) = TRUE
        OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) LIKE '%DIGITACAO_ERP%'
      )
    ),
    BOOL_OR(
      COALESCE(CFT.SELECIONADA, FALSE) = TRUE
      OR UPPER(COALESCE(CFT.STATUS, '')) = 'SELECIONADA'
    )
  INTO
    V_TOTAL_AUTOMATICAS,
    V_TOTAL_TRANSPORTADORAS_FLUXO,
    V_TOTAL_TRANSPORTADORAS_RESPONDIDAS,
    V_TEM_TRANSPORTADORA_ESCOLHIDA
  FROM COTACOES_FRETE_TRANSPORTADORAS CFT
  WHERE CFT.EMPRESA_ID = P_EMPRESA_ID
    AND CFT.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CFT.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CFT.CODIGO_CHAVE = P_CODIGO_CHAVE;

  V_POSSUI_ESCOLHA_REAL := COALESCE(V_TEM_TRANSPORTADORA_ESCOLHIDA, FALSE)
    OR V_ESCOLHIDO_EM IS NOT NULL
    OR V_ESCOLHIDO_POR_USUARIO_ID IS NOT NULL;

  IF UPPER(COALESCE(V_SITUACAO_PEDIDO, 'ATIVO')) <> 'ATIVO' THEN
    V_STATUS_NOVO := 'COTACAO_CANCELADA';
  ELSIF COALESCE(V_TOTAL_CTES, 0) > 0 OR COALESCE(V_NUMERO_CTE, '') <> '' OR V_CTE_RECEBIDO_EM IS NOT NULL THEN
    V_STATUS_NOVO := 'CTE_EMITIDO';
  ELSIF V_POSSUI_ESCOLHA_REAL THEN
    V_STATUS_NOVO := 'TRANSPORTADORA_ESCOLHIDA';
  ELSIF COALESCE(V_TOTAL_TRANSPORTADORAS_FLUXO, 0) > 0 THEN
    IF COALESCE(V_TOTAL_TRANSPORTADORAS_RESPONDIDAS, 0) >= COALESCE(V_TOTAL_TRANSPORTADORAS_FLUXO, 0) THEN
      V_STATUS_NOVO := 'EM_ANALISE';
    ELSE
      V_STATUS_NOVO := 'COTACAO_TRANSPORTADORA';
    END IF;
  ELSIF COALESCE(V_TOTAL_AUTOMATICAS, 0) > 0 THEN
    V_STATUS_NOVO := 'COTACAO_AUTOMATICA';
  ELSE
    V_STATUS_NOVO := 'COTACAO_PENDENTE';
  END IF;

  SELECT EK.ID
  INTO V_ETAPA_ID
  FROM ETAPAS_KANBAN EK
  INNER JOIN MODULOS M
    ON M.ID = EK.MODULO_ID
  WHERE EK.EMPRESA_ID = P_EMPRESA_ID
    AND M.CODIGO = 'COTACAO_FRETE'
    AND EK.CODIGO = V_STATUS_NOVO
    AND EK.ATIVA = TRUE
  ORDER BY EK.ORDEM ASC, EK.ID ASC
  LIMIT 1;

  UPDATE COTACOES_FRETE
  SET STATUS = V_STATUS_NOVO,
    ETAPA_KANBAN_ID = COALESCE(V_ETAPA_ID, ETAPA_KANBAN_ID),
    ALTERADO_EM = NOW()
  WHERE EMPRESA_ID = P_EMPRESA_ID
    AND TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CODIGO_CHAVE = P_CODIGO_CHAVE;
END;
$$;

DO $$
DECLARE
  REGISTRO RECORD;
BEGIN
  FOR REGISTRO IN
    SELECT EMPRESA_ID, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, CODIGO_CHAVE
    FROM COTACOES_FRETE
  LOOP
    PERFORM CONTROLSHUB_CALCULAR_STATUS_COTACAO(
      REGISTRO.EMPRESA_ID,
      REGISTRO.TIPO_DOCUMENTO,
      REGISTRO.NUMERO_DOCUMENTO,
      REGISTRO.CODIGO_CHAVE,
      TRUE
    );
  END LOOP;
END;
$$;
