-- CONTROL S HUB
-- Marca a transportadora escolhida na propria tabela de cotacoes por transportadora.
-- O ERP/N8N deve consumir a escolha por COTACOES_FRETE_TRANSPORTADORAS.ESCOLHIDA_PLATAFORMA.

ALTER TABLE PUBLIC.COTACOES_FRETE_TRANSPORTADORAS
  ADD COLUMN IF NOT EXISTS EMPRESA_ID BIGINT,
  ADD COLUMN IF NOT EXISTS TIPO_DOCUMENTO VARCHAR(40),
  ADD COLUMN IF NOT EXISTS NUMERO_DOCUMENTO VARCHAR(80),
  ADD COLUMN IF NOT EXISTS CODIGO_CHAVE VARCHAR(120),
  ADD COLUMN IF NOT EXISTS ESCOLHIDA_PLATAFORMA BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS SEQUENCIA INTEGER;

UPDATE PUBLIC.COTACOES_FRETE_TRANSPORTADORAS CFT
SET
  EMPRESA_ID = C.EMPRESA_ID,
  TIPO_DOCUMENTO = C.TIPO_DOCUMENTO,
  NUMERO_DOCUMENTO = C.NUMERO_DOCUMENTO,
  CODIGO_CHAVE = C.CODIGO_CHAVE
FROM PUBLIC.COTACOES_FRETE C
WHERE C.ID = CFT.COTACAO_FRETE_ID
  AND (
    CFT.EMPRESA_ID IS NULL
    OR CFT.TIPO_DOCUMENTO IS NULL
    OR CFT.NUMERO_DOCUMENTO IS NULL
    OR CFT.CODIGO_CHAVE IS NULL
  );

UPDATE PUBLIC.COTACOES_FRETE_TRANSPORTADORAS
SET ESCOLHIDA_PLATAFORMA = TRUE
WHERE COALESCE(SELECIONADA, FALSE) = TRUE;

CREATE INDEX IF NOT EXISTS IDX_COTACOES_FRETE_TRANSP_ESCOLHIDA_PLATAFORMA
  ON PUBLIC.COTACOES_FRETE_TRANSPORTADORAS (
    EMPRESA_ID,
    TIPO_DOCUMENTO,
    NUMERO_DOCUMENTO,
    CODIGO_CHAVE,
    ESCOLHIDA_PLATAFORMA
  );

CREATE INDEX IF NOT EXISTS IDX_COTACOES_FRETE_TRANSP_SEQUENCIA
  ON PUBLIC.COTACOES_FRETE_TRANSPORTADORAS (EMPRESA_ID, SEQUENCIA)
  WHERE SEQUENCIA IS NOT NULL;

CREATE OR REPLACE VIEW PUBLIC.VW_COTACOES_TRANSPORTADORAS_ESCOLHIDAS_ERP AS
SELECT
  C.EMPRESA_ID,
  C.TIPO_DOCUMENTO,
  C.NUMERO_DOCUMENTO,
  C.CODIGO_CHAVE,
  C.EMPRESA_ID || '|' || C.TIPO_DOCUMENTO || '|' || C.NUMERO_DOCUMENTO || '|' || C.CODIGO_CHAVE AS CHAVE_COTACAO,
  C.NUMERO_PEDIDO,
  C.DATA_DOCUMENTO,
  C.ORIGEM_COMERCIAL,
  C.NOME_DESTINATARIO,
  C.CIDADE_DESTINO,
  C.UF_DESTINO,
  C.VALOR_MERCADORIA,
  CFT.SEQUENCIA,
  CFT.TRANSPORTADORA_ID,
  CFT.CODIGO_TRANSPORTADORA,
  T.CODIGO_INTERNO AS CODIGO_INTERNO_TRANSPORTADORA,
  T.RAZAO_SOCIAL AS RAZAO_SOCIAL_TRANSPORTADORA,
  T.NOME_FANTASIA AS NOME_TRANSPORTADORA,
  CFT.VALOR_FRETE AS VALOR_FRETE_ESCOLHIDO,
  COALESCE(CFT.PRAZO_DIAS, 0) AS PRAZO_ESCOLHIDO_DIAS,
  CFT.ORIGEM_COTACAO,
  CFT.ORIGEM_DETALHADA,
  CFT.STATUS AS STATUS_TRANSPORTADORA,
  CFT.VALIDADA_EM AS ESCOLHIDA_EM,
  CFT.VALIDADA_POR_USUARIO_ID AS ESCOLHIDA_POR_USUARIO_ID,
  C.ATUALIZADO_NO_ERP,
  C.ATUALIZADO_NO_ERP_EM,
  C.BLOQUEADO_PARA_ALTERACAO
FROM PUBLIC.COTACOES_FRETE_TRANSPORTADORAS CFT
INNER JOIN PUBLIC.COTACOES_FRETE C
  ON C.EMPRESA_ID = CFT.EMPRESA_ID
 AND C.TIPO_DOCUMENTO = CFT.TIPO_DOCUMENTO
 AND C.NUMERO_DOCUMENTO = CFT.NUMERO_DOCUMENTO
 AND C.CODIGO_CHAVE = CFT.CODIGO_CHAVE
INNER JOIN PUBLIC.TRANSPORTADORAS T
  ON T.ID = CFT.TRANSPORTADORA_ID
WHERE COALESCE(C.EXCLUIDO, FALSE) = FALSE
  AND COALESCE(CFT.ESCOLHIDA_PLATAFORMA, FALSE) = TRUE
  AND COALESCE(C.ATUALIZADO_NO_ERP, FALSE) = FALSE;

CREATE OR REPLACE VIEW PUBLIC.VW_COTACOES_FRETE_PENDENTES_ERP AS
SELECT
  *
FROM PUBLIC.VW_COTACOES_TRANSPORTADORAS_ESCOLHIDAS_ERP
WHERE COALESCE(BLOQUEADO_PARA_ALTERACAO, FALSE) = FALSE;
