-- CONTROL S HUB
-- Consolida a regra definitiva de status operacional da cotacao.
-- Prioridade:
-- 1. Cancelada/excluida
-- 2. CT-e emitido
-- 3. Transportadora escolhida
-- 4. Em analise quando todos os links enviados foram respondidos
-- 5. Cotacao transportadora quando ainda ha link pendente
-- 6. Cotacao automatica quando existe cotacao automatica
-- 7. Cotacao pendente

ALTER TABLE cotacoes_frete
  ADD COLUMN IF NOT EXISTS atualizado_no_erp BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS atualizado_no_erp_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS retorno_erp_status VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
  ADD COLUMN IF NOT EXISTS retorno_erp_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS valor_frete_final NUMERIC(14, 2),
  ADD COLUMN IF NOT EXISTS prazo_final_dias INTEGER,
  ADD COLUMN IF NOT EXISTS motivo_escolha_transportadora_descricao TEXT;

ALTER TABLE cotacoes_frete_transportadoras
  ADD COLUMN IF NOT EXISTS empresa_id BIGINT,
  ADD COLUMN IF NOT EXISTS tipo_documento VARCHAR(30),
  ADD COLUMN IF NOT EXISTS numero_documento VARCHAR(80),
  ADD COLUMN IF NOT EXISTS codigo_chave VARCHAR(120),
  ADD COLUMN IF NOT EXISTS escolhida_plataforma BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS origem_detalhada VARCHAR(80),
  ADD COLUMN IF NOT EXISTS prazo_origem VARCHAR(40);

CREATE OR REPLACE FUNCTION CONTROLSHUB_CALCULAR_STATUS_COTACAO(
  P_EMPRESA_ID BIGINT,
  P_TIPO_DOCUMENTO VARCHAR,
  P_NUMERO_DOCUMENTO VARCHAR,
  P_CODIGO_CHAVE VARCHAR,
  P_FORCAR_RECALCULO BOOLEAN DEFAULT FALSE
)
RETURNS VOID
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_STATUS_NOVO VARCHAR(80);
  V_ETAPA_ID BIGINT;
  V_SITUACAO_PEDIDO VARCHAR(80);
  V_ESCOLHIDO_EM TIMESTAMPTZ;
  V_ESCOLHIDO_POR_USUARIO_ID BIGINT;
  V_TRANSPORTADORA_ESCOLHIDA_ID BIGINT;
  V_TOTAL_CTES INTEGER;
  V_TOTAL_AUTOMATICAS INTEGER;
  V_TOTAL_LINKS INTEGER;
  V_TOTAL_LINKS_PENDENTES INTEGER;
  V_TOTAL_TRANSPORTADORAS_EXTERNAS INTEGER;
  V_TEM_TRANSPORTADORA_SELECIONADA BOOLEAN;
  V_POSSUI_ESCOLHA_REAL BOOLEAN;
BEGIN
  SELECT
    COALESCE(C.SITUACAO_PEDIDO, 'ATIVO'),
    C.ESCOLHIDO_EM,
    C.ESCOLHIDO_POR_USUARIO_ID,
    C.TRANSPORTADORA_ESCOLHIDA_ID
  INTO
    V_SITUACAO_PEDIDO,
    V_ESCOLHIDO_EM,
    V_ESCOLHIDO_POR_USUARIO_ID,
    V_TRANSPORTADORA_ESCOLHIDA_ID
  FROM COTACOES_FRETE C
  WHERE C.EMPRESA_ID = P_EMPRESA_ID
    AND C.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND C.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND C.CODIGO_CHAVE = P_CODIGO_CHAVE
    AND COALESCE(C.EXCLUIDO, FALSE) = FALSE
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT COUNT(*)
  INTO V_TOTAL_CTES
  FROM COTACOES_FRETE_CTES CTE
  WHERE CTE.EMPRESA_ID = P_EMPRESA_ID
    AND CTE.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CTE.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CTE.CODIGO_CHAVE = P_CODIGO_CHAVE;

  SELECT COUNT(*)
  INTO V_TOTAL_AUTOMATICAS
  FROM COTACOES_FRETE_TRANSPORTADORAS CFT
  WHERE CFT.EMPRESA_ID = P_EMPRESA_ID
    AND CFT.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CFT.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CFT.CODIGO_CHAVE = P_CODIGO_CHAVE
    AND COALESCE(CFT.VALOR_FRETE, 0) > 0
    AND (
      UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) = 'COTACAO_AUTOMATICA'
      OR UPPER(COALESCE(CFT.ORIGEM_COTACAO, '')) IN ('AUTOMATICA', 'BANCO')
      OR (
        UPPER(COALESCE(CFT.ORIGEM_COTACAO, '')) = 'ERP'
        AND UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) <> 'DIGITACAO_ERP'
      )
    )
    AND UPPER(COALESCE(CFT.STATUS, '')) NOT IN (
      'COTACAO_TRANSPORTADORA_RECEBIDA',
      'RESPONDIDA',
      'ALTERADA_MANUALMENTE',
      'SELECIONADA',
      'ESCOLHIDA'
    );

  SELECT COUNT(*)
  INTO V_TOTAL_TRANSPORTADORAS_EXTERNAS
  FROM COTACOES_FRETE_TRANSPORTADORAS CFT
  WHERE CFT.EMPRESA_ID = P_EMPRESA_ID
    AND CFT.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CFT.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CFT.CODIGO_CHAVE = P_CODIGO_CHAVE
    AND (
      UPPER(COALESCE(CFT.ORIGEM_COTACAO, '')) NOT IN ('ERP', 'AUTOMATICA', 'BANCO')
      OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) = 'DIGITACAO_ERP'
      OR UPPER(COALESCE(CFT.STATUS, '')) IN ('COTACAO_TRANSPORTADORA_RECEBIDA', 'RESPONDIDA', 'ALTERADA_MANUALMENTE')
    );

  WITH LINKS_ENVIADOS AS (
    SELECT DISTINCT ON (TOK.TRANSPORTADORA_ID)
      TOK.TRANSPORTADORA_ID,
      TOK.TOKEN_HASH,
      TOK.NUMERO_ENVIO
    FROM COTACOES_FRETE_TOKENS TOK
    WHERE TOK.EMPRESA_ID = P_EMPRESA_ID
      AND TOK.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
      AND TOK.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
      AND TOK.CODIGO_CHAVE = P_CODIGO_CHAVE
      AND TOK.TRANSPORTADORA_ID IS NOT NULL
      AND COALESCE(TOK.STATUS, '') <> 'CANCELADO'
    ORDER BY
      TOK.TRANSPORTADORA_ID,
      TOK.GERADO_EM DESC NULLS LAST,
      TOK.NUMERO_ENVIO DESC NULLS LAST,
      TOK.TOKEN_HASH DESC
  ),
  ESTADOS_LINKS AS (
    SELECT
      LINK.TRANSPORTADORA_ID,
      EXISTS (
        SELECT 1
        FROM COTACOES_FRETE_TRANSPORTADORAS CFT
        WHERE CFT.EMPRESA_ID = P_EMPRESA_ID
          AND CFT.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
          AND CFT.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
          AND CFT.CODIGO_CHAVE = P_CODIGO_CHAVE
          AND CFT.TRANSPORTADORA_ID = LINK.TRANSPORTADORA_ID
          AND (
            UPPER(COALESCE(CFT.ORIGEM_COTACAO, '')) NOT IN ('ERP', 'AUTOMATICA', 'BANCO')
            OR UPPER(COALESCE(CFT.ORIGEM_DETALHADA, '')) = 'DIGITACAO_ERP'
            OR UPPER(COALESCE(CFT.STATUS, '')) IN ('COTACAO_TRANSPORTADORA_RECEBIDA', 'RESPONDIDA', 'ALTERADA_MANUALMENTE')
          )
          AND (
            CFT.RESPONDIDA_EM IS NOT NULL
            OR CFT.COTADA_EM IS NOT NULL
            OR UPPER(COALESCE(CFT.STATUS, '')) IN ('COTACAO_TRANSPORTADORA_RECEBIDA', 'RESPONDIDA', 'ALTERADA_MANUALMENTE')
          )
      ) AS RESPONDEU
    FROM LINKS_ENVIADOS LINK
  )
  SELECT
    COUNT(*),
    COUNT(*) FILTER (WHERE RESPONDEU = FALSE)
  INTO
    V_TOTAL_LINKS,
    V_TOTAL_LINKS_PENDENTES
  FROM ESTADOS_LINKS;

  SELECT BOOL_OR(
    COALESCE(CFT.SELECIONADA, FALSE) = TRUE
    OR COALESCE(CFT.ESCOLHIDA_PLATAFORMA, FALSE) = TRUE
    OR UPPER(COALESCE(CFT.STATUS, '')) IN ('SELECIONADA', 'ESCOLHIDA')
  )
  INTO V_TEM_TRANSPORTADORA_SELECIONADA
  FROM COTACOES_FRETE_TRANSPORTADORAS CFT
  WHERE CFT.EMPRESA_ID = P_EMPRESA_ID
    AND CFT.TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND CFT.NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CFT.CODIGO_CHAVE = P_CODIGO_CHAVE;

  V_POSSUI_ESCOLHA_REAL := V_TRANSPORTADORA_ESCOLHIDA_ID IS NOT NULL
    OR V_ESCOLHIDO_EM IS NOT NULL
    OR V_ESCOLHIDO_POR_USUARIO_ID IS NOT NULL
    OR COALESCE(V_TEM_TRANSPORTADORA_SELECIONADA, FALSE) = TRUE;

  IF UPPER(COALESCE(V_SITUACAO_PEDIDO, 'ATIVO')) <> 'ATIVO' THEN
    V_STATUS_NOVO := 'COTACAO_CANCELADA';
  ELSIF COALESCE(V_TOTAL_CTES, 0) > 0 THEN
    V_STATUS_NOVO := 'CTE_EMITIDO';
  ELSIF V_POSSUI_ESCOLHA_REAL THEN
    V_STATUS_NOVO := 'TRANSPORTADORA_ESCOLHIDA';
  ELSIF COALESCE(V_TOTAL_LINKS, 0) > 0 THEN
    IF COALESCE(V_TOTAL_LINKS_PENDENTES, 0) = 0 THEN
      V_STATUS_NOVO := 'EM_ANALISE';
    ELSE
      V_STATUS_NOVO := 'COTACAO_TRANSPORTADORA';
    END IF;
  ELSIF COALESCE(V_TOTAL_TRANSPORTADORAS_EXTERNAS, 0) > 0 THEN
    V_STATUS_NOVO := 'COTACAO_TRANSPORTADORA';
  ELSIF COALESCE(V_TOTAL_AUTOMATICAS, 0) > 0 THEN
    V_STATUS_NOVO := 'COTACAO_AUTOMATICA';
  ELSE
    V_STATUS_NOVO := 'COTACAO_PENDENTE';
  END IF;

  SELECT EK.ID
  INTO V_ETAPA_ID
  FROM ETAPAS_KANBAN EK
  INNER JOIN MODULOS M
    ON M.ID = EK.MODULO_ID
  WHERE EK.EMPRESA_ID = P_EMPRESA_ID
    AND M.CODIGO = 'COTACAO_FRETE'
    AND EK.CODIGO = V_STATUS_NOVO
    AND EK.ATIVA = TRUE
  ORDER BY EK.ORDEM ASC, EK.ID ASC
  LIMIT 1;

  UPDATE COTACOES_FRETE
  SET STATUS = V_STATUS_NOVO,
    ETAPA_KANBAN_ID = COALESCE(V_ETAPA_ID, ETAPA_KANBAN_ID),
    ALTERADO_EM = NOW()
  WHERE EMPRESA_ID = P_EMPRESA_ID
    AND TIPO_DOCUMENTO = P_TIPO_DOCUMENTO
    AND NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO
    AND CODIGO_CHAVE = P_CODIGO_CHAVE
    AND COALESCE(EXCLUIDO, FALSE) = FALSE;
END;
$$;

CREATE OR REPLACE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_EMPRESA_ID BIGINT;
  V_TIPO_DOCUMENTO VARCHAR;
  V_NUMERO_DOCUMENTO VARCHAR;
  V_CODIGO_CHAVE VARCHAR;
BEGIN
  IF PG_TRIGGER_DEPTH() > 1 THEN
    RETURN NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    V_EMPRESA_ID := OLD.EMPRESA_ID;
    V_TIPO_DOCUMENTO := OLD.TIPO_DOCUMENTO;
    V_NUMERO_DOCUMENTO := OLD.NUMERO_DOCUMENTO;
    V_CODIGO_CHAVE := OLD.CODIGO_CHAVE;
  ELSE
    V_EMPRESA_ID := NEW.EMPRESA_ID;
    V_TIPO_DOCUMENTO := NEW.TIPO_DOCUMENTO;
    V_NUMERO_DOCUMENTO := NEW.NUMERO_DOCUMENTO;
    V_CODIGO_CHAVE := NEW.CODIGO_CHAVE;
  END IF;

  PERFORM CONTROLSHUB_CALCULAR_STATUS_COTACAO(
    V_EMPRESA_ID,
    V_TIPO_DOCUMENTO,
    V_NUMERO_DOCUMENTO,
    V_CODIGO_CHAVE,
    FALSE
  );

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS TG_CONTROLSHUB_STATUS_COTACAO_CABECALHO ON COTACOES_FRETE;
CREATE TRIGGER TG_CONTROLSHUB_STATUS_COTACAO_CABECALHO
AFTER INSERT OR UPDATE OF STATUS, SITUACAO_PEDIDO, TRANSPORTADORA_ESCOLHIDA_ID, ESCOLHIDO_EM, ESCOLHIDO_POR_USUARIO_ID, BLOQUEADO_PARA_ALTERACAO
ON COTACOES_FRETE
FOR EACH ROW
EXECUTE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO();

DROP TRIGGER IF EXISTS TG_CONTROLSHUB_STATUS_COTACAO_TRANSPORTADORA ON COTACOES_FRETE_TRANSPORTADORAS;
CREATE TRIGGER TG_CONTROLSHUB_STATUS_COTACAO_TRANSPORTADORA
AFTER INSERT OR UPDATE OR DELETE
ON COTACOES_FRETE_TRANSPORTADORAS
FOR EACH ROW
EXECUTE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO();

DROP TRIGGER IF EXISTS TG_CONTROLSHUB_STATUS_COTACAO_CTE ON COTACOES_FRETE_CTES;
CREATE TRIGGER TG_CONTROLSHUB_STATUS_COTACAO_CTE
AFTER INSERT OR UPDATE OR DELETE
ON COTACOES_FRETE_CTES
FOR EACH ROW
EXECUTE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO();

DO $$
DECLARE
  REGISTRO RECORD;
BEGIN
  FOR REGISTRO IN
    SELECT EMPRESA_ID, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, CODIGO_CHAVE
    FROM COTACOES_FRETE
    WHERE COALESCE(EXCLUIDO, FALSE) = FALSE
  LOOP
    PERFORM CONTROLSHUB_CALCULAR_STATUS_COTACAO(
      REGISTRO.EMPRESA_ID,
      REGISTRO.TIPO_DOCUMENTO,
      REGISTRO.NUMERO_DOCUMENTO,
      REGISTRO.CODIGO_CHAVE,
      TRUE
    );
  END LOOP;
END;
$$;
