-- CONTROL S HUB
-- Impede que a reintegracao do pedido ou alteracoes de ofertas reabram fluxos ja definidos.
-- Mantem intacta a regra existente das respostas/bolinhas para cotacoes em andamento.

CREATE OR REPLACE FUNCTION CONTROLSHUB_TRIGGER_STATUS_COTACAO()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_EMPRESA_ID BIGINT;
  V_TIPO_DOCUMENTO VARCHAR;
  V_NUMERO_DOCUMENTO VARCHAR;
  V_CODIGO_CHAVE VARCHAR;
  V_STATUS_ATUAL VARCHAR;
BEGIN
  IF PG_TRIGGER_DEPTH() > 1 THEN
    RETURN NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    V_EMPRESA_ID := OLD.EMPRESA_ID;
    V_TIPO_DOCUMENTO := OLD.TIPO_DOCUMENTO;
    V_NUMERO_DOCUMENTO := OLD.NUMERO_DOCUMENTO;
    V_CODIGO_CHAVE := OLD.CODIGO_CHAVE;
  ELSE
    V_EMPRESA_ID := NEW.EMPRESA_ID;
    V_TIPO_DOCUMENTO := NEW.TIPO_DOCUMENTO;
    V_NUMERO_DOCUMENTO := NEW.NUMERO_DOCUMENTO;
    V_CODIGO_CHAVE := NEW.CODIGO_CHAVE;
  END IF;

  SELECT C.STATUS
  INTO V_STATUS_ATUAL
  FROM COTACOES_FRETE C
  WHERE C.EMPRESA_ID = V_EMPRESA_ID
    AND C.TIPO_DOCUMENTO = V_TIPO_DOCUMENTO
    AND C.NUMERO_DOCUMENTO = V_NUMERO_DOCUMENTO
    AND C.CODIGO_CHAVE = V_CODIGO_CHAVE
    AND COALESCE(C.EXCLUIDO, FALSE) = FALSE
  LIMIT 1;

  IF UPPER(COALESCE(V_STATUS_ATUAL, '')) IN (
    'COTACAO_CANCELADA',
    'TRANSPORTADORA_ESCOLHIDA',
    'CTE_EMITIDO',
    'EM_ANALISE',
    'BLOQUEADO_FINALIZADO'
  ) THEN
    RETURN NULL;
  END IF;

  PERFORM CONTROLSHUB_CALCULAR_STATUS_COTACAO(
    V_EMPRESA_ID,
    V_TIPO_DOCUMENTO,
    V_NUMERO_DOCUMENTO,
    V_CODIGO_CHAVE,
    FALSE
  );

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION controlshub_preservar_cotacao_protegida()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_STATUS_OLD VARCHAR;
  V_STATUS_NEW VARCHAR;
BEGIN
  V_STATUS_OLD := UPPER(COALESCE(OLD.STATUS, ''));
  V_STATUS_NEW := UPPER(COALESCE(NEW.STATUS, ''));

  IF V_STATUS_OLD IN ('COTACAO_CANCELADA', 'TRANSPORTADORA_ESCOLHIDA', 'CTE_EMITIDO', 'EM_ANALISE', 'BLOQUEADO_FINALIZADO')
    AND V_STATUS_NEW IN ('RECEBIDO_ERP', 'COTACAO_PENDENTE', 'COTACAO_AUTOMATICA', '') THEN
    NEW.STATUS := OLD.STATUS;
    NEW.ETAPA_KANBAN_ID := OLD.ETAPA_KANBAN_ID;
    NEW.TRANSPORTADORA_ESCOLHIDA_ID := OLD.TRANSPORTADORA_ESCOLHIDA_ID;
    NEW.TRANSPORTADORA_ESCOLHIDA_CODIGO := OLD.TRANSPORTADORA_ESCOLHIDA_CODIGO;
    NEW.TRANSPORTADORA_ESCOLHIDA_NOME := OLD.TRANSPORTADORA_ESCOLHIDA_NOME;
    NEW.VALOR_FRETE_ESCOLHIDO := OLD.VALOR_FRETE_ESCOLHIDO;
    NEW.PRAZO_ESCOLHIDO_DIAS := OLD.PRAZO_ESCOLHIDO_DIAS;
    NEW.VALOR_FRETE_FINAL := OLD.VALOR_FRETE_FINAL;
    NEW.PRAZO_FINAL_DIAS := OLD.PRAZO_FINAL_DIAS;
    NEW.ESCOLHIDO_EM := OLD.ESCOLHIDO_EM;
    NEW.ESCOLHIDO_POR_USUARIO_ID := OLD.ESCOLHIDO_POR_USUARIO_ID;
    NEW.MOTIVO_ESCOLHA_TRANSPORTADORA_ID := OLD.MOTIVO_ESCOLHA_TRANSPORTADORA_ID;
    NEW.MOTIVO_ESCOLHA_TRANSPORTADORA_DESCRICAO := OLD.MOTIVO_ESCOLHA_TRANSPORTADORA_DESCRICAO;
    NEW.ATUALIZADO_NO_ERP := OLD.ATUALIZADO_NO_ERP;
    NEW.ATUALIZADO_NO_ERP_EM := OLD.ATUALIZADO_NO_ERP_EM;
    NEW.RETORNO_ERP_STATUS := OLD.RETORNO_ERP_STATUS;
    NEW.RETORNO_ERP_EM := OLD.RETORNO_ERP_EM;
    NEW.ALTERADO_EM := OLD.ALTERADO_EM;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_controlshub_preservar_cotacao_protegida ON cotacoes_frete;
CREATE TRIGGER tg_controlshub_preservar_cotacao_protegida
BEFORE UPDATE ON cotacoes_frete
FOR EACH ROW
EXECUTE FUNCTION controlshub_preservar_cotacao_protegida();

CREATE OR REPLACE FUNCTION controlshub_preservar_transportadoras_cotacao_protegida()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
DECLARE
  V_STATUS VARCHAR;
  V_EMPRESA_ID BIGINT;
  V_TIPO_DOCUMENTO VARCHAR;
  V_NUMERO_DOCUMENTO VARCHAR;
  V_CODIGO_CHAVE VARCHAR;
BEGIN
  V_EMPRESA_ID := COALESCE(OLD.EMPRESA_ID, NEW.EMPRESA_ID);
  V_TIPO_DOCUMENTO := COALESCE(OLD.TIPO_DOCUMENTO, NEW.TIPO_DOCUMENTO);
  V_NUMERO_DOCUMENTO := COALESCE(OLD.NUMERO_DOCUMENTO, NEW.NUMERO_DOCUMENTO);
  V_CODIGO_CHAVE := COALESCE(OLD.CODIGO_CHAVE, NEW.CODIGO_CHAVE);

  SELECT UPPER(COALESCE(C.STATUS, ''))
  INTO V_STATUS
  FROM COTACOES_FRETE C
  WHERE C.EMPRESA_ID = V_EMPRESA_ID
    AND C.TIPO_DOCUMENTO = V_TIPO_DOCUMENTO
    AND C.NUMERO_DOCUMENTO = V_NUMERO_DOCUMENTO
    AND C.CODIGO_CHAVE = V_CODIGO_CHAVE
    AND COALESCE(C.EXCLUIDO, FALSE) = FALSE
  LIMIT 1;

  IF V_STATUS IN ('COTACAO_CANCELADA', 'TRANSPORTADORA_ESCOLHIDA', 'CTE_EMITIDO', 'EM_ANALISE', 'BLOQUEADO_FINALIZADO') THEN
    IF TG_OP = 'DELETE' THEN
      RETURN NULL;
    END IF;

    IF TG_OP = 'UPDATE'
      AND UPPER(COALESCE(NEW.STATUS, '')) = 'RECEBIDA'
      AND UPPER(COALESCE(NEW.ORIGEM_COTACAO, '')) IN ('ERP', 'AUTOMATICA', 'BANCO') THEN
      RETURN OLD;
    END IF;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_controlshub_preservar_transportadoras_cotacao_protegida ON cotacoes_frete_transportadoras;
CREATE TRIGGER tg_controlshub_preservar_transportadoras_cotacao_protegida
BEFORE UPDATE OR DELETE ON cotacoes_frete_transportadoras
FOR EACH ROW
EXECUTE FUNCTION controlshub_preservar_transportadoras_cotacao_protegida();
